export type PieceId =
  'dark-rook-1' |
  'dark-knight-1' |
  'dark-bishop-1' |
  'dark-queen' |
  'dark-king' |
  'dark-bishop-2' |
  'dark-knight-2' |
  'dark-rook-2' |
  'dark-pawn-1' |
  'dark-pawn-2' |
  'dark-pawn-3' |
  'dark-pawn-4' |
  'dark-pawn-5' |
  'dark-pawn-6' |
  'dark-pawn-7' |
  'dark-pawn-8' |
  'light-rook-1' |
  'light-knight-1' |
  'light-bishop-1' |
  'light-queen' |
  'light-king' |
  'light-bishop-2' |
  'light-knight-2' |
  'light-rook-2' |
  'light-pawn-1' |
  'light-pawn-2' |
  'light-pawn-3' |
  'light-pawn-4' |
  'light-pawn-5' |
  'light-pawn-6' |
  'light-pawn-7' |
  'light-pawn-8';