// <auto-generated />
using System;
using Chess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241123040538_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Chess.Models.Entities.Game", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Ending")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PlayerOneId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerTwoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TimeControlIncrement")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TimeControlTime")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TimeRemainingBlack")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("TimeRemainingWhite")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Winner")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TimeControlTime", "TimeControlIncrement");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Chess.Models.Entities.TimeControl", b =>
                {
                    b.Property<ulong>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Increment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Time", "Increment");

                    b.ToTable("TimeControls");
                });

            modelBuilder.Entity("Chess.Models.Entities.Game", b =>
                {
                    b.HasOne("Chess.Models.Entities.TimeControl", "TimeControl")
                        .WithMany()
                        .HasForeignKey("TimeControlTime", "TimeControlIncrement")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeControl");
                });
#pragma warning restore 612, 618
        }
    }
}
